server:
  address: "tcp://:9091"
theme: "dark"
log:
  level: "warn"
  format: "text"
  file_path: "/log/authelia.log"
totp:
  issuer: "sub0.net"
identity_validation:
  reset_password:
    jwt_secret: {{ secret "/secrets/identity_validation/reset_password/jwt_secret" }}
authentication_backend:
  file:
    path: "/data/users_database.yml"
access_control:
  default_policy: "deny"
  rules:
    # admin group gets access to anything with 2FA
    - domain_regex: "[a-z0-9]*.sub0.net"
      policy: "one_factor"
      subject:
        - "group:admins"
    # per-service access groups
    - domain_regex:
        - '^(?P<Group>\w+)\.sub0\.net$'
      policy: one_factor
    # unconfigured subdomain gets
    - domain_regex: "[a-z0-9]*.sub0.net"
      policy: deny
session:
  secret: {{ secret "/secrets/session/secret" }}
  cookies:
    - name: "sub0_session"
      domain: "sub0.net" # Should match whatever your root protected domain is
      authelia_url: "https://auth.sub0.net"
      expiration: "1 hour"
      inactivity: "5 minutes"
  redis:
    host: "redis"
    port: 6379
    password: {{ secret "/secrets/session/redis/password" }}
# ban for 5 minutes if there are 3 failed password attempts in 2 minutes
regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"
storage:
  encryption_key: {{ secret "/secrets/storage/encryption_key" }}
  local:
    path: "/data/db.sqlite3"
# Notifier file for password reset and TOTP confirmation
# TODO: setup SMTP server for email
notifier:
  disable_startup_check: false
  filesystem:
    filename: "/data/notification.txt"
# OpenID Connect configuration
identity_providers:
  oidc:
    hmac_secret: {{ secret "/secrets/identity_providers/oidc/hmac_secret" }}
    jwks:
      - algorithm: "RS256"
        use: "sig"
        key: {{ secret "/secrets/identity_providers/oidc/jwks/key" | mindent 10 "|" | msquote }}
    clients:
      - client_name: "Actual"
        client_id: {{ secret "/secrets/identity_providers/oidc/clients/actual/id" }}
        client_secret: {{ secret "/secrets/identity_providers/oidc/clients/actual/secret" }}
        public: false
        authorization_policy: "one_factor"
        redirect_uris:
          - "https://actual.sub0.net/openid/callback"
        scopes:
          - "email"
          - "groups"
          - "openid"
          - "profile"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_basic"
