keys:
  - &users:
    - &parthiv age1rjtjx0fuuad84jv4v63nctnrkd35xarg3fxmdldjk0dnfqdese7s534sx4
  - &hosts:
    - &midnight age1qxj3v7m9vt3qg7zs2563x40qdg988r3qjg3k93rdpnq37fgm24lqf9s8ca
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *parthiv
      - *midnight
