services:
  server:
    image: "jellyfin/jellyfin"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    networks:
      traefik_proxy:
    devices:
      # pass thru iGPU for quicksync
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /var/lib/jellyfin/config:/config
      - /var/lib/jellyfin/cache:/cache
      - /data/nobackup/media/Movies:/Movies:ro
      - /data/nobackup/media/Shows:/Shows:ro
    labels:
      - "traefik.enable=true"
      # redirect HTTP to HTTPS
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.sub0.net`)"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      # configure jellyfin HTTPS
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.sub0.net`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=traefik_proxy"
      # Enable authelia
      - "traefik.http.routers.jellyfin-secure.middlewares=authelia@docker"
networks:
  traefik_proxy:
    external: true
