name: "Nix Code Quality"
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25

      # nixfmt-rfc-style: check formatting
      - name: Check formatting with nixfmt-rfc-style
        run: |
          find . -name '*.nix' -print0 | xargs -0 nix run nixpkgs#nixfmt-rfc-style -- --check

      # statix: lint Nix code
      - name: Lint Nix code with statix
        run: |
          nix run nixpkgs#statix -- check .

      # deadnix: detect dead code
      - name: Check for dead Nix code with deadnix
        run: |
          nix run nixpkgs#deadnix -- .

