name: "Build NixOS Configurations (ARM)"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        host: [ nimbus ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Load SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Build NixOS configuration
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
