name: "Evaluate NixOS Configurations"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [ icicle, midnight, nimbus, vardar ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Load SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Evaluate NixOS configuration
        run: nix eval .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
