name: "Nix Code Quality"
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Check formatting with nixfmt-rfc-style
        run: |
          find . -name '*.nix' -print0 | xargs -0 nix run nixpkgs#nixfmt-rfc-style -- --check
      - name: Lint Nix code with statix
        run: |
          nix run nixpkgs#statix -- check .
      - name: Check for dead Nix code with deadnix
        run: |
          nix run nixpkgs#deadnix -- .
