name: "Build and Cache NixOS Configurations"
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [icicle, midnight, nimbus]
    steps:
      - name: Set up QEMU for aarch64
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      - name: Maximize disk space for Nix
        uses: wimpysworld/nothing-but-nix@main
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: |
            build-dir = /nix/build
            extra-platforms = aarch64-linux
            extra-substituters = https://cache.nixos-cuda.org
            extra-trusted-public-keys = cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M=
      - name: Load SSH private key for secrets repo
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Build configuration
        run: |
          nix build --no-link .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
      - name: Add cache host key
        run: |
          mkdir -p ~/.ssh
          echo "cache.sub0.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHoePjXvae+ZXjjMaCEUG+UQj1wDaGjAvygU47rxhaGy" >> ~/.ssh/known_hosts
      - name: Push to cache
        continue-on-error: true
        run: |
          path=$(nix path-info .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel)
          nix copy --to ssh://nix-cache@cache.sub0.net $path
          ssh nix-cache@cache.sub0.net "nix-store --add-root /nix/var/nix/gcroots/cache/${{ matrix.host }} -r $path"
